# config: https://yamllint.readthedocs.io/en/stable/configuration.html
# rules: https://yamllint.readthedocs.io/en/stable/rules.html
---
extends: default

rules:
  braces:
    max-spaces-inside: 1
  line-length: disabled
