# BREWFILE

## Brews

brew 'bash'
brew 'bash-git-prompt'
brew 'coreutils'
brew 'docker'
brew 'fzf'
brew 'git'
brew 'go'
brew 'htop'
brew 'hub'
brew 'hugo'
brew 'jq'
brew 'kubernetes-cli'
brew 'make'
brew 'shellcheck'
brew 'stow'
brew 'terraform'
brew 'tmux'
brew 'vault'
brew 'vim'
brew 'yamllint'

## Casks
# tap 'caskroom/cask'
# cask '1password'
# cask 'docker'
# cask 'dropbox'
# cask 'firefox'
# cask 'font-sourcecodepro-nerd-font'
# cask 'google-chrome'
# cask 'iterm2'
# cask 'slack'
# cask 'spectacle'
# cask 'spotify'
# cask 'vagrant'
# cask 'virtualbox'
