# https://starship.rs/config/
# for custom symbols: https://www.nerdfonts.com/cheat-sheet

format = """\
	$directory\
	$git_branch\
	$git_commit\
	$git_state\
	$git_status\
	$package\
	$golang\
	$nodejs\
	$python\
	$ruby\
	$rust\
	$aws\
	$env_var\
	$docker_context\
	$kubernetes\
	$battery\
	$memory_usage\
	$time\
	$jobs\
	$cmd_duration\
	$line_break\
	$character
"""

[aws]
symbol = " "
format = "[$symbol$profile(\\($region\\))]($style) "

[battery]
disabled = false
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 20
style = "red"

[[battery.display]]
threshold = 60
style = "yellow"

[[battery.display]]
threshold = 100
style = "green"

[cmd_duration]
style = "dimmed"
format = "[duration:$duration]($style)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
deleted = "x"
show_sync_count = true
style = "red"
format = "[$all_status$ahead_behind]($style) "

[rust]
symbol = " "
format = "[$symbol$version]($style) "

[ruby]
symbol = " "
format = "[$symbol$version]($style) "

[golang]
symbol = " "
format = "[$symbol$version]($style) "

[nodejs]
symbol = " "
format = "[$symbol$version]($style) "

[package]
symbol = " "
format = "[$symbol$version]($style) "

[docker_context]
symbol= " "
format = "[$symbol$context]($style) "

[kubernetes]
symbol = "ﴱ "
disabled = false
format = "[$symbol$context(\\($namespace\\))]($style) "

[jobs]
symbol = " "

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"
