# https://starship.rs/config/
# for custom symbols: https://www.nerdfonts.com/cheat-sheet

prompt_order = [
	"username",
	"hostname",
	"directory",
	"git_branch",
	"git_commit",
	"git_state",
	"git_status",
	"package",
	"golang",
	"nodejs",
	"python",
	"ruby",
	"rust",
	"terraform",
	"conda",
	"aws",
	"env_var",
	"kubernetes",
	"battery",
	"memory_usage",
	"jobs",
	"line_break",
	"character",
]

[aws]
symbol = " "

[battery]
disabled = false
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 20
style = "red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 60
style = "yellow"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 100
style = "green"

[memory_usage]
disabled = false
show_percentage = true
show_swap = false
threshold = 0
symbol = " "
style = "dimmed white"

[git_branch]
symbol = " "

[git_status]
deleted = "x"
show_sync_count = true

[rust]
symbol = " "

[ruby]
symbol = " "

[golang]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[package]
symbol = " "

[terraform]
symbol = " "

[docker]
symbol= " "

[kubernetes]
symbol = "ﴱ "
disabled = false

[jobs]
symbol = "%"
style = "blue"

[character]
symbol = "$"
