# https://starship.rs/config/
# for custom symbols: https://www.nerdfonts.com/cheat-sheet

prompt_order = [
	# "username",
	# "hostname",
	"directory",
	"git_branch",
	"git_commit",
	"git_state",
	"git_status",
	"package",
	"golang",
	"nodejs",
	"python",
	"ruby",
	"rust",
	"terraform",
	"conda",
	"aws",
	"env_var",
	"docker_context",
	"kubernetes",
	"battery",
	"memory_usage",
	"jobs",
	"cmd_duration",
	"line_break",
	"character",
]

[aws]
symbol = "aws:"

[directory]
truncation_length = 0

[battery]
disabled = false
full_symbol = "batt:"
charging_symbol = "batt:"
discharging_symbol = "batt:"

[[battery.display]]
threshold = 20
style = "red"

[[battery.display]]
threshold = 60
style = "yellow"

[[battery.display]]
threshold = 100
style = "green"

[memory_usage]
disabled = false
show_percentage = true
show_swap = false
threshold = 0
symbol = "mem:"
style = "dimmed"

[git_branch]
symbol = "git:"

[git_status]
deleted = "x"
show_sync_count = true
style = "red"

[rust]
symbol = "rust:"

[ruby]
symbol = "ruby:"

[golang]
symbol = "go:"

[nodejs]
symbol = "node:"

[python]
symbol = "python:"

[package]
symbol = "package:"

[terraform]
symbol = "terraform:"

[docker_context]
symbol= "docker:"

[kubernetes]
symbol = "k8s:"
disabled = false

[jobs]
symbol = "%"

[character]
symbol = "$"
style_success = "green"
style_failure = "red"
