# https://starship.rs/config/

prompt_order = [
	# "username",
	# "hostname",
	"directory",
	"git_branch",
	"git_commit",
	"git_state",
	"git_status",
	"package",
	"dotnet",
	"golang",
	"java",
	"nodejs",
	"php",
	"python",
	"ruby",
	"rust",
	"terraform",
	"nix_shell",
	"conda",
	"aws",
	"env_var",
	"kubernetes",
	"jobs",
	"line_break",
	"character",
]

[aws]
symbol = " "

[git_branch]
symbol = " "

[rust]
symbol = " "

[golang]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[kubernetes]
symbol = "ﴱ "
disabled = false

[character]
symbol = "$"
