[options]
  background = "light"
  bootstrap_after = "custom#after"
  bootstrap_before = "custom#before"
  buffer_index_type = 4
  colorscheme = "one"
  colorscheme_bg = "light"
  enable_ale = true
  enable_cursorline = false
  enable_guicolors = true
  enable_neomake = false
  enable_statusline_display_mode = false
  enable_tabline_filetype_icon = true
  filemanager = "nerdtree"
  relativenumber = 0
  statusline_inactive_separator = "nil"
  statusline_separator = "nil"
  terminal_cursor_shape = 0

[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 20

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "incsearch"

[[layers]]
  name = "fzf"

[[layers]]
  name = "default"

[[layers]]
  name = "checkers"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

# Languages
[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#vim"

# Custom Plugins
[[custom_plugins]]
  name = "hashivim/vim-hashicorp-tools"

[[custom_plugins]]
  name = "airblade/vim-gitgutter"
