#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  bootstrap_before = "custom#before"
  bootstrap_after = "custom#after"
  buffer_index_type = 4
  colorscheme = "one"
  colorscheme_bg = "light"
  enable_ale = true
  enable_guicolors = true
  enable_neomake = false
  enable_statusline_display_mode = false
  enable_tabline_filetype_icon = true
  filemanager = "nerdtree"
  statusline_inactive_separator = "arrow"
  statusline_separator = "nil"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "incsearch"

[[layers]]
  name = "fzf"

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#go"

[[layers]]
# npm install --global vscode-html-languageserver-bin
  name = "lang#html"

[[layers]]
  name = "lang#javascript"
  auto_fix = true

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "tmux"

[[layers]]
# npm -g install remark
# npm -g install remark-cli
# npm -g install remark-stringify
  name = "lang#markdown"

[[layers]]
# pip install --user flake8
# pip install --user yapf
# pip install --user autoflake
# pip install --user isort
  name = "lang#python"

[[layers]]
# gem install rubocop
  name = "lang#ruby"

[[layers]]
# npm i -g typescript
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"

[[layers]]
# npm install -g javascript-typescript-langserver
# go get -u github.com/sourcegraph/go-langserver
# npm install --save vscode-html-languageservice
  name = "lsp"
  filetypes = [ "go" ]

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "default"

[[layers]]
  name = "checkers"
