# BREWFILE

## Brews

# brew 'awscli'
# brew 'docker'
# brew 'fzf'
# brew 'go'
# brew 'hub'
# brew 'hugo'
brew 'bash'
brew 'coreutils'
brew 'gimme'
brew 'git'
brew 'htop'
brew 'jq'
brew 'kubectl'
brew 'neovim'
brew 'python'
brew 'python@2'
brew 'terraform'
brew 'vault'
brew 'vim'

## Casks
tap 'caskroom/cask'

# cask 'dropbox'
# cask 'firefox'
# cask 'google-chrome'
# cask 'vagrant'
# cask 'virtualbox'
cask '1password'
cask 'docker'
cask 'font-sourcecodepro-nerd-font'
cask 'iterm2'
cask 'slack'
cask 'spectacle'
cask 'spotify'
