#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https:##spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    filetype_icon = true
    statusline_display_mode = false
    filemanager = "nerdtree"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'colorscheme'
[[layers]]
name = 'fzf'
[[layers]]
name = 'git'
[[layers]]
name = 'github'
[[layers]]
name = 'incsearch'
[[layers]]
name = 'tmux'

# Languages
[[layers]]
name = 'lang#go'
[[layers]]
name = 'lang#javascript'
[[layers]]
name = 'lang#json'
[[layers]]
name = 'lang#markdown'
[[layers]]
name = 'lang#python'
[[layers]]
name = 'lang#ruby'
[[layers]]
name = 'lang#rust'
[[layers]]
name = 'lang#sh'
[[layers]]
name = 'lang#tmux'
[[layers]]
name = 'lang#toml'
[[layers]]
name = 'lang#typescript'
[[layers]]
name = 'lang#xml'
